# This will most likely match the group/repo in github.
org: zprobst
app: my-awesome-service

accounts:
  default:
    id: 123456789
    regions:
      - us-east-1
      - us-west-1
  prod:
    id: 123456789
    regions:
      - us-east-1
      - us-west-1

approvals:
  prod:
    type: slack
    people:
      - "@zprobst"
      - "@jsmith"

triggers:
  - pr:
      deploy: true
  - merge:
      to: master        # This can be any regular expression.
      deploy: 
        - stage
  - tag:
      pattern: semver   # Semver is a special value. This can be any regular expression.
      deploy:
        - prod

stages:
  - name: stage
  - name: prod
    approvers: prod
    account: prod
