# This will most likely match the group/repo in github.
org: resilient-vitality
app: api

# Conveyor supports multiple accounts and curretly only aws.
accounts:
  aws:
    - name: default
      id: 123456789
      regions:
        - us-east-1
        - us-west-1
    - name: prod
      id: 123456789
      regions:
        - us-east-1
        - us-west-1
  
# Approvals are currently supported with slack.
approvals:
  prod:
    type: slack
    people:
      - "@zprobst"
      - "@jsmith"

# Triggers are evaluted and performed in order. 
# If there are any triggers that are relevant given the event, we
# first build the code, and perform the triggers in this order.
# 
# You can imagine the algorithm as:
#
# for triggers in relevant_triggers
#   for stage in triggers.deploy:
#     stage.deploy(code_sha)
# 
# Prs and system operations are evaluated before the triggers specified here.

triggers:
  - pr: true
    deploy: true
  - merge: master
    deploy: 
      - stage
  - tag: semver   # Semver is a special value. This can be any regular expression.
    deploy:
      - prod

stages:
  - stage
  - name: prod
    approvers: prod
    account: prod

# This is the most explict way possible. The order of matching a configuration
# is the following:
# 1.) Whatever is specified
# 2.) Something with the name of the stage.
# 3.) Something called default for that type.
#     So we can rewrite the prod stage the same as stage with just the name specified.
#     
#     Pr Builds and deploys tirgger when there is an update or a creation of a pr.
#     Specified approvals are required when the stage is going to be deployed to the stage
#     when the 